var CORE_ASSETS = [
  './',
  './splash.html',                    // ← YANGI
  './image/entering-picture.png',     // ← YANGI
  './menu/menu.html',
  './menu/menu.css',
  './menu/menu.js',
  './game.html',
  './game.css',
  './game.js',
  './loading.html',
  './lang.js',
  './save.js',
  './audio.js',
  './music.js',
  './world.js',
  './weapons.js',
  './zombies.js',
  './items.js',
  './ai.js',
  './player.js',
  './help.js',
  './plane.js',
  './missions.js',
  './hud.js',
  './controller.js',
  './pwa.js',
  './manifest.json',
  './image/letfordead.png'
];